language: node_js
node_js:
  - 4.0.0
before_install:
  - npm install -g jest-cli
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
notifications:
  email:
    recipients:
      - contactsamie@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always